[project]
version = "0.1.2"
name = "project"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
ast = "*"
pool = "*"
list = "*"
log = "*"
mem = "*"
os = "*"
path = "*"
runtime_assert = "*"
slice = "*"
string = "*"
toml = "*"

[repos]
list = "git://github.com/zzmodules/list"
os = "git://github.com/zzmodules/os"
path = "git://github.com/zzmodules/path"
runtime_assert = "git://github.com/zzmodules/runtime-assert"
